import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import Header from '@/components/Header'
import MaxWidthWrapper from '@/components/MaxWidthWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, user, team
}: {
  children: React.ReactNode,
  user: React.ReactNode,
  team: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={cn(
        'min-h-screen font-sans subpixel-antialiased grainy'
      )}>
        <Header href='/dashboard'/>
        <MaxWidthWrapper className='flex flex-row justify-center divide-x-2'>
          {user}
          {team}
        </MaxWidthWrapper>
        {children}
      </body>
    </html>
  )
}
